---

- hosts: 127.0.0.1
  become: yes
  tasks:
  - name: PWD
    command: sudo pwd

  - name: date
    command: sudo date

  - name: exe test_script.sh
    script: ./test_script

  - name: create testFile.txt file
    file:
      name: /assets/testFile.txt
      state: touch

  - name: log output
    lineinfile:   ### add lines to files
      line: "here is some text"   ### the line to add
      path: /assets/testFile.txt  ### the filepath to the file we want to manipulate with 'lineinfile'