AWSTemplateFormatVersion: 2010-09-09
Description: Project 1 with CloudFormation, VividCloud Training.

Resources:

  MyS3Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
        - "arn:aws:iam::aws:policy/AWSXrayFullAccess"
        - "arn:aws:logs:*:*:log-group:/aws/lambda-insights:*"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole


  function:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt MyS3Role.Arn
      Code:
        S3Bucket: bucketyboop-us-east-1
        S3Key: s3index.zip
      Handler: index.handler
      Runtime: nodejs14.x
      TracingConfig:
        Mode: Active

## Deploying this

## TODO
## Add Xray permissions. And a Log Group
##    Log groups need to exsist before the lambda function can use them DependsOn: LogGroupA
## Work with DynamoDb tables
##    Log data from one table to another
## API Gateway? more lambdas. 
## Add VPC, Networking
## EC2 Instance to host a site?