AWSTemplateFormatVersion: 2010-09-09
Description: Project 1 with CloudFormation, VividCloud Training.

Resources:

  MyS3Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - sts:AssumeRole

  function:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt MyS3Role.Arn
      Code:
        S3Bucket: bucketyboop-us-east-1
        S3Key: index.zip
      Handler: index.handler
      Runtime: nodejs14.x
      TracingConfig:
        Mode: Active
## Deploying this
