# Variables
- name: Vars File
  include_vars:
    file: "vars/main.yml"

# requirements for AWS module
- name: Pip3 install boto, botocore, and boto3
  pip:
    name:
    - boto
    - boto3
    - botocore
  
# Create a stack
- name: Create CF stack with AWS CF module
  amaonz.aws.cloudformation:
    stacK_name: Ansible-Built-Stack
    state: present
    region: us-east-1
    template_url: https://cf-templates-b1xw4f0m3hhk-us-east-1.s3.amazonaws.com/2021159XS0-template.yaml
    # disable_rollback: yes
    # template: assets/cfstack.yml
    # template_parameters:
    #   KeyName: "jmartin"
    #   DiskType: "ephemeral"
    #   InstanceType: "m1.small"
    #   ClusterSize: 3
    tags:
      Stack: "ansible-cloudformation"

##### FROM ANSIBLE DOCS #####

# Basic role example
# - name: create a stack, specify role that cloudformation assumes
#   amazon.aws.cloudformation:
#     stack_name: Ansible-Built-Stack
#     state: "present"
#     region: "us-east-1"
#     disable_rollback: true
#     template: "roles/cloudformation/files/cloudformation-example.json"
#     role_arn: 'arn:aws:iam::123456789012:role/cloudformation-iam-role'
